zip(region, weights)      # zip pairs the data as tuplesm

# 3 Numpy library

## 3.1 Arrays in Numpy

In [ ]:
"""
Numpy library is built for big numerical computations. It has build-in functions
that are It is written in C++ which is about 100x faster than python itself.
"""

#!pip install numpy --upgrade --quiet   # installing numpy library if needed
import numpy as np                      # aliasing to use np instead of numpy each time

1D_array = np.array([1, 2, 3])          # not a list anymore, but a 1D array

2D_array = np.array([[73, 67, 43],      # 2D array
                     [91, 88, 64],      # a list of 5 elements, 
                     [87, 134, 58],     # where each element contains a list of 3 elements
                     [102, 43, 37],
                     [69, 96, 70]])

3D_array = np.array([                   # 3D array 
            [[11, 12, 13], 
             [13, 14, 15]], 
            [[15, 16, 17], 
             [17, 18, 19.5]]])

np.ones((3,2))                          # matrix with only ones
np.zeros((2,2))                         # matrix with only zeros
np.eye(2)                               # identity matrix with 2 rows, 2 columns
np.full([2, 2], 8)                      # 2 rows, 2 columns, fixed value 8
np.random.rand(3)                       # 1 row, 3 elements, random numbers
np.random.randn(2,3)                    # same but random number from normal distribution
np.arrange(5, 11, 2)                    # list with start, end and steps
np.linspace(3, 27, 9)                   # equally spaced numbers in a range
empty_list = np.empty(5)                # empty list with 5 spaces
empty_list.fill(2)                      # every element in list becomes 2

# np.reshape, np.stack, np.concatenate, np.split

print(3D_array[0, 2, 2])       # access a single element
print(3D_array[1:, 0:1, 0])    # 
print(3D_array[1])             # access first row

In [30]:
# math operations

arr_1 = np.array([1.5, 2, 3, 5])

round_arr_1 = np.round(arr_1, 1)            # round every element up to 1 decimal
sum_arr_1 = np.sum(arr_1)                   # sum of every element in array
exp_arr_1 = np.exp(arr_1)                   # every element e^x
sqrt_arr_1 = np.sqrt(arr_1)                 # every element sqrt(x)
log_arr_1 = np.log(arr_1)                   # every element log(x)

"""
Broadcasting is one array adjusting shape (copying itself) to match shape
of other array so it can be added, improves performance and saves memory.
"""

arr_1 = np.array([[1, 2], 
                  [2, 2]])
arr_2 = np.array([1, 1])
sum_broadcasting = arr_1 + arr_2

print('The broadcasting sum is')
print(sum_broadcasting)

The broadcasting sum is
[[2 3]
 [3 3]]


In [35]:
# linear algebra

arr_1 = np.array([1.5, 2, 3])

arr_2 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

arr_3 = np.array([2, 3, 4])

dimensions = arr_2.shape
transposed_arr_2 = np.transpose(arr_2)
determinant_arr_2 = np.linalg.det(arr_2)
sum_of_product_of_arrays = np.dot(arr_1, arr_3)
matrix_multiplication = arr_1 @ arr_3

print("Dimensions of arr_2 are {}".format(dimensions))
print("Transposed arr_2 is")
print(transposed_arr_2)
print("Determinant of arr_2 is {}".format(np.round(determinant_arr_2, 17)))
print("Sum of product of arr_1 and arr_2 is {}".format(sum_of_product_of_arrays))
print("Matrix multiplication of arr_1 and arr_3 is {}".format(matrix_multiplication))

Dimensions of arr_2 are (3, 3)
Transposed arr_2 is
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinant of arr_2 is 6.7e-16
Sum of product of arr_1 and arr_2 is 21.0
Matrix multiplication of arr_1 and arr_3 is 21.0


## 3.2 Statistics

In [3]:
mean_arr_1 = np.mean(arr_1)
median_arr_1 = np.median(arr_1)
stdv_arr_1 = np.std(arr_1)
max_arr_1 = np.max(arr_1)
min_arr_1 = np.min(arr_1)

3.0

## 3.3 Manipulate a csv

In [42]:
import numpy as np

climate_data = np.genfromtxt('climate.csv', delimiter=',', skip_header=1)
print(climate_data)

w1, w2, w3 = 0.3, 0.2, 0.5
weights = np.array([w1, w2, w3])
yields = climate_data @ weights

climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis = 1)
print()
print(climate_results)

np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yield_apples', 
           comments='')

[[25. 76. 99.]
 [39. 65. 70.]
 [59. 45. 77.]
 ...
 [99. 62. 58.]
 [70. 71. 91.]
 [92. 39. 76.]]

[[25.  76.  99.  72.2]
 [39.  65.  70.  59.7]
 [59.  45.  77.  65.2]
 ...
 [99.  62.  58.  71.1]
 [70.  71.  91.  80.7]
 [92.  39.  76.  73.4]]
